//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bhaptics.SDK2
{
    using System;
    using UnityEngine;
    
    
    public class BhapticsEvent
    {
        
        public const string RIDINGVEHICLE = "ridingvehicle";
        
        public const string ATTACKED_HEAD_WEAK = "attacked_head_weak";
        
        public const string RUNNING = "running";
        
        public const string ATTACKED_BODY_STRONG = "attacked_body_strong";
        
        public const string HIT_STRONG_LEFT = "hit_strong_left";
        
        public const string HIT_WEAK_LEFT = "hit_weak_left";
        
        public const string ATTACKED_BODY_WEAK = "attacked_body_weak";
        
        public const string GAME_START = "game_start";
        
        public const string HIT_STRONG_RIGHT = "hit_strong_right";
        
        public const string WINGSUITFLYING = "wingsuitflying";
        
        public const string ATTACKED_HEAD_STRONG = "attacked_head_strong";
        
        public const string HIT_WEAK_RIGHT = "hit_weak_right";
    }
}
